# Generated by Django 5.0.7 on 2024-07-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpassword',
            name='include_numbers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generatedpassword',
            name='include_special',
            field=models.BooleanField(default=True),
        ),
    ]
